import {assumptions,routePoints,estimateCycle,sampleStation,colorRGB} from './thermo34.mjs';
import {MAX_PARTICLES,particleCount,particleSample} from './particle40.mjs';
const $=s=>document.querySelector(s);
export function createLab({THREE,scene,camera,controls,groups,rotors,casing,flowGroup,axialScale,axialOffset,showModel,getState}){
 let cycle=estimateCycle(),mapping='temperature',shaft=false,focus='both',tour=false,tourRun=false,u=0,probe=false,lastUI=-1,restoreView=null,savedOpacity=35;
 const hud=document.createElement('section');hud.id='lab-hud';hud.hidden=true;hud.innerHTML=`<div id="hud-tour" hidden><strong>跟随一团空气</strong><div class="hud-maps" role="group" aria-label="导览空气着色变量"><button data-color-map="temperature" aria-pressed="true" class="active">按总温着色</button><button data-color-map="pressure" aria-pressed="false">按总压着色</button></div><label for="tour-station">到达站位</label><select id="tour-station" aria-label="导览站位"></select><p id="hud-values"></p><div class="hud-legend"><span id="hud-low"></span><i id="hud-ramp" class="color-ramp"></i><span id="hud-high"></span></div><div class="two-buttons"><button id="hud-play">暂停导览</button><button id="hud-exit">退出导览</button></div><small>总参数 · 概念估算，非实测</small></div><div id="hud-shaft" hidden><strong>轴系联动</strong><div class="shaft-buttons" role="group" aria-label="模型内轴系聚焦"><button data-spool-focus="both" class="active" aria-pressed="true">双轴联动</button><button data-spool-focus="hp" aria-pressed="false">高压轴</button><button data-spool-focus="lp" aria-pressed="false">低压轴</button></div><p>高压橙色 / 低压蓝色<br>反向旋转 · 演示速比 2∶1</p><button id="hud-shaft-exit">恢复整机着色</button></div>`;$('#model-pane').append(hud);
 $('#tour-station').innerHTML=cycle.stations.map(s=>`<option value="${s.u}">${s.name}</option>`).join('');
 const chartWrap=document.createElement('div');chartWrap.className='chart-scroll';$('#station-chart').before(chartWrap);chartWrap.append($('#station-chart'));
 const revealModel=()=>$('#model-pane').scrollIntoView({behavior:'instant',block:'center'});
 const originals=new Map(),aux=new THREE.Group();aux.userData.lab=true;scene.add(aux);
 const path=new THREE.CatmullRomCurve3(routePoints.map(([x,r])=>new THREE.Vector3(x,r,0)),false,'centripetal');
 // All particles travel through an annulus, including its folded combustor section.
 const at=(t,angle=0,jitter=0)=>{const v=path.getPoint(Math.max(0,Math.min(1,t)));const r=v.y+jitter;return new THREE.Vector3(v.x*axialScale+axialOffset,r*Math.cos(angle),r*Math.sin(angle));};
 const tempColor=t=>{const s=sampleStation(cycle,t),state=getState(),cold=state.starting||!state.on;return new THREE.Color(...colorRGB(mapping==='temperature'?(cold?assumptions.T0:s.T):(cold?assumptions.p0:s.p),mapping==='temperature'?assumptions.T0:cycle.minP,mapping==='temperature'?cycle.maxT:cycle.maxP,mapping)).convertSRGBToLinear();};
 const count=MAX_PARTICLES,positions=new Float32Array(count*6),colors=new Float32Array(count*6),geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.BufferAttribute(positions,3));geo.setAttribute('color',new THREE.BufferAttribute(colors,3));
 const trails=new THREE.LineSegments(geo,new THREE.LineBasicMaterial({vertexColors:true,transparent:true,opacity:.82,depthWrite:false,toneMapped:false}));aux.add(trails);
 const pointsGeo=new THREE.BufferGeometry();pointsGeo.setAttribute('position',new THREE.BufferAttribute(new Float32Array(count*3),3));pointsGeo.setAttribute('color',new THREE.BufferAttribute(new Float32Array(count*3),3));
 const dots=new THREE.Points(pointsGeo,new THREE.PointsMaterial({size:.055,vertexColors:true,transparent:true,opacity:.85,depthWrite:false,toneMapped:false}));aux.add(dots);
 const bundleControls=document.createElement('div');bundleControls.className='bundle-controls';bundleControls.innerHTML='<label><input id="single-bundle" type="checkbox">仅显示单束气流</label><span id="bundle-status">周向多束 · 24 束</span><small>保留原流路与温压着色；粒子数量不代表质量流量。</small>';$('.color-controls').after(bundleControls);
 $('#single-bundle').onchange=()=>{const single=$('#single-bundle').checked;$('#bundle-status').textContent=single?'单束气流 · 从周向多束中保留 1 束':'周向多束 · 24 束';const n=particleCount(single);geo.setDrawRange(0,n*2);pointsGeo.setDrawRange(0,n);};
 const parcel=new THREE.Group();aux.add(parcel);const markerMat=new THREE.MeshBasicMaterial({color:0xf0a344,transparent:true,opacity:.95,depthTest:false,toneMapped:false});
 for(let i=0;i<19;i++){const m=new THREE.Mesh(new THREE.SphereGeometry(i===0?.12:.025,10,7),markerMat);if(i)m.position.set(.07*Math.sin(i*2.4),.10*Math.cos(i*2.4),.10*Math.sin(i*2.4));parcel.add(m);}
 const halo=new THREE.Mesh(new THREE.SphereGeometry(.20,16,12),new THREE.MeshBasicMaterial({color:0xf0a344,transparent:true,opacity:.16,depthWrite:false,depthTest:false,toneMapped:false}));parcel.add(halo);parcel.renderOrder=5;
 const plane=new THREE.Mesh(new THREE.RingGeometry(.72,1.38,64),new THREE.MeshBasicMaterial({color:0x448ab4,transparent:true,opacity:.35,side:THREE.DoubleSide,depthWrite:false,toneMapped:false}));plane.rotation.y=Math.PI/2;aux.add(plane);
 const rotorOwner=new Map();rotors.filter(r=>r.spool!=='prop').forEach(r=>r.object.traverse(o=>{if(o.isMesh)rotorOwner.set(o,r.spool);}));
 [...groups,casing,...rotors.map(r=>r.object)].filter(Boolean).forEach(g=>g.traverse(o=>{if(o.isMesh&&!originals.has(o))originals.set(o,{color:o.material.color.clone(),opacity:o.material.opacity,transparent:o.material.transparent,depthWrite:o.material.depthWrite,emissive:o.material.emissive?.clone(),metalness:o.material.metalness});}));
 function repaintShaft(){for(const [o,m] of originals){if(!shaft){o.material.color.copy(m.color);if(m.emissive)o.material.emissive.copy(m.emissive);o.material.metalness=m.metalness;continue;}const spool=rotorOwner.get(o),active=spool&&(focus==='both'||spool===focus);o.material.color.set(spool==='hp'?0xb16842:spool==='lp'?0x3b7794:0xa8b5b5);o.material.transparent=true;o.material.opacity=active?1:spool?.24:.09;o.material.depthWrite=!!active;o.material.metalness=active?.35:m.metalness;if(o.material.emissive)o.material.emissive.set(active?(spool==='hp'?0x311609:0x09212d):0x000000);} }
 function restoreMaterials(){for(const [o,m] of originals){o.material.color.copy(m.color);o.material.opacity=m.opacity;o.material.transparent=m.transparent;o.material.depthWrite=m.depthWrite;o.material.metalness=m.metalness;if(m.emissive)o.material.emissive.copy(m.emissive);}$('#opacity').value=savedOpacity;$('#opacity').dispatchEvent(new Event('input'));}
 function shaftSet(value){if(value){stopTour();savedOpacity=Number($('#opacity').value);showModel();shaft=true;$('#shaft-mode').checked=true;$('#shaft-controls').hidden=false;repaintShaft();revealModel();}else{shaft=false;$('#shaft-mode').checked=false;$('#shaft-controls').hidden=true;restoreMaterials();}applyVisibility();}
 function applyVisibility(){const s=getState(),model=s.tab==='model'&&!s.isolated&&!['exploded','hp','lp'].includes(s.mode);if(flowGroup){flowGroup.visible=model&&!shaft&&$('#flow-toggle').checked;flowGroup.children.forEach(o=>{if(o.isLine)o.visible=$('#flow-toggle').checked;});}trails.visible=dots.visible=model&&!shaft&&s.on&&$('#particles-toggle').checked;parcel.visible=model&&tour&&!shaft;plane.visible=model&&probe&&!shaft;hud.hidden=!model||(!tour&&!shaft);$('.stage').classList.toggle('lab-active',!hud.hidden);$('.stage').classList.toggle('lab-shaft',shaft);$('#hud-tour').hidden=!tour;$('#hud-shaft').hidden=!shaft;if(shaft)repaintShaft();}
 function saveCamera(){restoreView={position:camera.position.clone(),target:controls.target.clone()};}
 function stopTour(){if(!tour)return;tour=false;tourRun=false;$('#tour-play').textContent='开始导览';$('#tour-marker').hidden=true;controls.enabled=true;if(restoreView){camera.position.copy(restoreView.position);controls.target.copy(restoreView.target);restoreView=null;}$('#opacity').value=savedOpacity;$('#opacity').dispatchEvent(new Event('input'));applyVisibility();}
 function beginTour(){if(shaft)shaftSet(false);if(!tour){showModel();savedOpacity=Number($('#opacity').value);saveCamera();tour=true;$('#opacity').value=12;$('#opacity').dispatchEvent(new Event('input'));revealModel();}controls.enabled=false;$('#tour-marker').hidden=false;applyVisibility();}
 $('#shaft-mode').onchange=e=>shaftSet(e.target.checked);
 document.querySelectorAll('[data-spool-focus]').forEach(b=>b.onclick=()=>{if(!shaft)shaftSet(true);focus=b.dataset.spoolFocus;document.querySelectorAll('[data-spool-focus]').forEach(n=>{const active=n.dataset.spoolFocus===focus;n.classList.toggle('active',active);n.setAttribute('aria-pressed',String(active));});repaintShaft();});
 $('#tour-play').onclick=()=>{beginTour();tourRun=!tourRun;if(u>=1)u=0;$('#tour-play').textContent=tourRun?'暂停导览':'继续导览';updateUI();};$('#tour-stop').onclick=stopTour;
 $('#tour-progress').oninput=e=>{beginTour();tourRun=false;u=Number(e.target.value)/100;$('#tour-play').textContent='继续导览';updateUI();};
 $('#tour-station').onchange=e=>{beginTour();tourRun=false;u=Number(e.target.value);$('#tour-play').textContent='继续导览';updateUI();};$('#hud-play').onclick=()=>$('#tour-play').click();$('#hud-exit').onclick=stopTour;$('#hud-shaft-exit').onclick=()=>shaftSet(false);
 document.querySelectorAll('[data-color-map]').forEach(b=>b.onclick=()=>{mapping=b.dataset.colorMap;document.querySelectorAll('[data-color-map]').forEach(n=>{const active=n.dataset.colorMap===mapping;n.classList.toggle('active',active);n.setAttribute('aria-pressed',String(active));});updateUI();});
 $('#probe-enabled').onchange=e=>{probe=e.target.checked;if(probe&&!tour)showModel();applyVisibility();};$('#probe-progress').oninput=updateUI;
 $('#lab-open').onclick=()=>{$('#explorer-lab').open=true;$('#explorer-lab').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});};
 $('#operating-mode').addEventListener('change',updateUI);
 const recalc=()=>{cycle=estimateCycle({T4:Number($('#cycle-t4').value),load:Number($('#cycle-load').value)});updateUI();drawChart();};$('#cycle-t4').oninput=recalc;$('#cycle-load').oninput=recalc;
 function readout(prefix,t){const s=sampleStation(cycle,t),cold=getState().starting||!getState().on;$('#'+prefix+'-temperature').textContent=cold?'—':Math.round(s.T);$('#'+prefix+'-pressure').textContent=cold?'—':s.p.toFixed(1);$('#'+prefix+'-region').textContent=s.region;return s;}
 function updateUI(){const s=readout('tour',u),pu=Number($('#probe-progress').value)/100,cold=getState().starting||!getState().on;readout('probe',pu);$('#tour-progress').value=u*100;$('#tour-progress-value').value=Math.round(u*100)+'%';$('#probe-progress-value').value=Math.round(pu*100)+'%';$('#tour-process').textContent=s.note;$('#cycle-t4-value').value=cycle.T4+' K';$('#cycle-load-value').value=cycle.load+' kJ/kg';$('#cycle-status').textContent=cycle.warning;$('#cycle-status').classList.toggle('warn',!cycle.valid);$('#color-title').textContent=mapping==='temperature'?'总温着色 / K':'总压着色 / kPa';$('#color-ramp').classList.toggle('pressure',mapping==='pressure');$('#color-low').textContent=mapping==='temperature'?Math.round(assumptions.T0):cycle.minP.toFixed(1);$('#color-high').textContent=mapping==='temperature'?Math.round(cycle.maxT):cycle.maxP.toFixed(1);$('#tour-marker').textContent=s.name+' · '+(cold?'无稳态值':mapping==='temperature'?Math.round(s.T)+' K':s.p.toFixed(1)+' kPa');$('#hud-values').textContent=cold?'起动 / 停机：不显示稳态值':`${Math.round(s.T)} K · ${s.p.toFixed(1)} kPa`;$('#hud-ramp').classList.toggle('pressure',mapping==='pressure');$('#hud-low').textContent=$('#color-low').textContent;$('#hud-high').textContent=$('#color-high').textContent;$('#hud-play').textContent=$('#tour-play').textContent;const closest=cycle.stations.reduce((a,b)=>Math.abs(b.u-u)<Math.abs(a.u-u)?b:a);$('#tour-station').value=closest.u;$('#cycle-power').textContent=`高压压气机 ${cycle.wHP.toFixed(1)} / 低压压气机 ${cycle.wLP.toFixed(1)} / 电机与附件负载 ${cycle.load} kJ/kg`;drawChart();}
 function drawChart(){const svg=$('#station-chart'),W=850,H=300,left=62,right=765,top=26,bottom=205,tx=t=>left+t*(right-left),ty=t=>bottom-(t-200)/(1600-200)*(bottom-top),py=p=>bottom-p/650*(bottom-top);let h='';for(let i=0;i<=4;i++){const y=bottom-i*(bottom-top)/4;h+=`<path d="M${left} ${y}H${right}" stroke="#d2ded8"/><text x="${left-8}" y="${y+4}" text-anchor="end">${200+i*350}</text><text x="${right+8}" y="${y+4}">${(i*162.5).toFixed(0)}</text>`;}const pts=f=>cycle.stations.map(s=>tx(s.u)+','+f(s)).join(' ');h+=`<polyline points="${pts(s=>ty(s.T))}" fill="none" stroke="#bc713c" stroke-width="3"/><polyline points="${pts(s=>py(s.p))}" fill="none" stroke="#397c9c" stroke-width="3"/>`;cycle.stations.forEach((s,i)=>{h+=`<circle cx="${tx(s.u)}" cy="${ty(s.T)}" r="3" fill="#bc713c"/><text x="${tx(s.u)}" y="${227+i%2*20}" text-anchor="middle">${['入口','进气','低压压缩','轴流级','斜流级','供气腔','燃烧','折返出口','高压涡轮','低压涡轮','喷管'][i]}</text>`;});const probeU=Number($('#probe-progress').value)/100;h+=`<path d="M${tx(probeU)} ${top}V${bottom}" stroke="#77988a" stroke-dasharray="4 4"/><text x="${left}" y="16" fill="#bc713c">总温 K</text><text x="${right}" y="16" fill="#397c9c">总压 kPa</text>`;svg.innerHTML=h;}
 function update(dt,time){const s=getState();applyVisibility();if(shaft)repaintShaft();const visibleCount=particleCount($('#single-bundle').checked);for(let i=0;i<visibleCount;i++){const {phase,angle:a,jitter}=particleSample(i,time),p=at(phase,a,jitter),q=at(Math.max(0,phase-.009),a-.01,jitter),c=tempColor(phase);p.toArray(positions,i*6);q.toArray(positions,i*6+3);c.toArray(colors,i*6);c.clone().multiplyScalar(.7).toArray(colors,i*6+3);p.toArray(pointsGeo.attributes.position.array,i*3);c.toArray(pointsGeo.attributes.color.array,i*3);}geo.attributes.position.needsUpdate=geo.attributes.color.needsUpdate=pointsGeo.attributes.position.needsUpdate=pointsGeo.attributes.color.needsUpdate=true;
 if(tour){if(tourRun&&s.playing&&s.on){u=Math.min(1,u+dt*s.speed/30);if(u===1){tourRun=false;$('#tour-play').textContent='重新导览';}}const p=at(u,-.34),c=tempColor(u);parcel.position.copy(p);markerMat.color.copy(c);halo.material.color.copy(c);const dir=at(Math.min(.9999,u+.012),-.34).sub(at(Math.max(.0001,u-.012),-.34)).normalize(),eye=p.clone().add(new THREE.Vector3(-2.6,2.1,5.6));camera.position.lerp(eye,.09);controls.target.lerp(p.clone().addScaledVector(dir,.4),.15);}
 if(probe){const pu=Number($('#probe-progress').value)/100,p=at(pu);plane.position.set(p.x,0,0);plane.material.color.copy(tempColor(pu));plane.scale.setScalar(Math.max(.5,p.y/1.05));}
 if(time-lastUI>.15||time<lastUI){lastUI=time;updateUI();}if(tour){const p=parcel.position.clone().project(camera),r=$('#viewport').getBoundingClientRect();$('#tour-marker').style.left=Math.max(100,Math.min(r.width-100,(p.x*.5+.5)*r.width))+'px';$('#tour-marker').style.top=Math.max(115,Math.min(r.height-100,(-p.y*.5+.5)*r.height-45))+'px';}
 }
 document.querySelectorAll('[data-mode], [data-tab], [data-view], #reset, #isolate, #combust-view').forEach(b=>b.addEventListener('click',()=>{if(tour)stopTour();if(shaft)shaftSet(false);}));
 updateUI();return {update,applyVisibility,at,getCycle:()=>cycle,reset:()=>{if(tour)stopTour();if(shaft)shaftSet(false);}};
}
